name_line_1: "MICHAEL R."
name_line_2: "BERTHOLD"
address: "123 Anywhere St., Any City, ST 12345"
phone: "Tel: 123-456-789"
email: "hello@reallygreatsite.com"
linkedin_url: "https://www.linkedin.com/"
scholar_url: "https://scholar.google.com/"
